#! /bin/sh

### BEGIN INIT INFO
# Provides:          homer_script
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Simple script to start a program at boot
# Description:       A simple script from www.stuffaboutcode.com which will start / stop a program a boot / shutdown.
### END INIT INFO

/bin/bash /home/ubuntu/homer_face.sh

# If you want a command to always run, put it he
exit 0
